jorgenschaefer/elpy

test/test-helper.el

I assume this is the right spot to put this?

Make tests less verbose by restricting yasnippet output.

---

elpy.el
test/elpy-importmagic--add-import-read-args-test.el

Do not try to get an import statement if no choices are available.

---

elpy.el

check if derived mode is python mode

---

elpy.el

switch between python shell and buffer

---

docs/editing.rst

just an update in relation with the commit fb68aa01bb4ccce0420766264e8757c2b2487ac8 about the block indent removal

update the documentation to match last block indent changes

---

elpy.el
test/elpy-nav-expand-to-indentation-test.el

Not sure which key binding to use for this. Suggestions?
closes #616

Add function to select surrounding lines with current indentation

---

elpy.el

Use custom symbol for regexp search

---

elpy.el
test/elpy-shell-send-current-statement.el

@jorgenschaefer  I tried  to add a test case similar to `elpy-shell-send-region-or-buffer-should-send-region-if-active`, but it is executing entire buffer?
closes #381

Add function to send current statement to Python shell

---

elpy/ropebackend.py

Catch rope refactoring error in backend

---

elpy/refactor.py

Ensure rope is installed before refactoring code

---

elpy.el
test/elpy-autopep8-fix-code-test.el

Retain point while autopep8 refactoring

---

elpy/ropebackend.py

Catch all rope exceptions when calling rope

---

elpy.el

I find it useful, but i am still skeptical whether it should be added to elpy or not.

Retain point when expanding to indentation

---

elpy/auto_pep8.py

Use configuration options while pep8 fixing

---

elpy/refactor.py

Rope shouldn't refactor without project root

---

elpy.el

Restart rpc process when virtualenv is activated

---

elpy/ropebackend.py

Catch rope attribute error

---

elpy.el

Looks like I left these two out in my last PR from a while back.

Add ^ specifier to two more -nav commands

---

elpy/ropebackend.py

Catch all rope exceptions

---

elpy.el

Add config option to disable backed error display

---

elpy.el
test/elpy-goto-definition-other-window-test.el
test/elpy-goto-location-test.el

Added elpy-goto-definition-other-window

---

elpy/refactor.py

Catch refactoring error

---

docs/editing.rst

Update documentation for moving by indentation

---

elpy.el
test/elpy-check-test.el

Use extra arguments depending on lint checker

---

elpy.el
test/elpy-config-test.el

Set python-check-command correctly

---

elpy.el
test/elpy-yapf-fix-code-test.el

Improve cursor positioning while format

---

elpy/tests/test_yapf.py
elpy/yapfutil.py
test/elpy-yapf-fix-code-test.el

Catch yapf exceptions

---

elpy.el

Sorry for the tiny pull requests...

elpy.el: fix typo __main__ -> __name__

---

elpy-shell.el
elpy.el

Fixes #1205, #1210, #1219. 
Also various smaller improvements in elpy-shell.

elpy-shell: Non-blocking capturing of output, minor improvements, and bugfixes

---

elpy.el
test/elpy-test-green-runner-test.el

Add support for the [Green](https://github.com/CleanCut/green) test runner.
Following discussion #1222.

Add Green test runner

---

elpy/jedibackend.py

Remove special cases of jedi failing, since most of those issues have
been fixed in the newer releases

Clean up jedi backend

---

elpy.el
test/elpy-rpc-get-completions-test.el

Elpy won't offer completion if the symbol at point is a number.
Should fix #1115.

Don't offer completion on numbers

---

docs/ide.rst
elpy.el
elpy/auto_pep8.py
elpy/server.py
elpy/tests/test_auto_pep8.py
elpy/tests/test_server.py
elpy/tests/test_yapf.py
elpy/yapfutil.py

Copy of the PR #989 from @jonmoore.
Plus some documentation for the potential users of yapf style file.

Source yapf file from project root

---

elpy-shell.el

elisp is not python - triple quotes are not okay.

Bug fix: elpy-shell-send-file was not interactive. 

---

README.rst

Add Debian (and derivatives) installation instructions.

---

elpy.el

Just add some details on the version mismatch error message (see #1137).
This should makes version mismatch easier to fix for users.

Add some details on the version mismatch error message

---

elpy.el

Fix #1386.
For emacs >= 26.1, python.el supports flymake.
With both elpy and python.el performing the syntax check, we end up with redundant syntax check errors.
This commit removes a part of elpy's flymake module (only for emacs >= 26.1) to avoid
performing the syntax check twice.

Remove redundant flake8 checks for emacs >= 26.1

---

.travis.yml
test/elpy-flymake-show-error-test.el
test/elpy-module-flymake-test.el

Just add emacs 26.1 to travis.

Add emacs 26.1 to travis

---

elpy-shell.el

Reverts jorgenschaefer/elpy#1427. See discussion in #1424

Revert "Fix echoing output in the minibuffer"

---

elpy.el
test/elpy-company-backend-test.el

Fix byte compile error due to `add-to-list`

---

elpy/jedibackend.py

Following #1495.
Minor fix of a forgotten if statement in oneline_docstring.

Fix corner case

---

elpy.el

Docstring typo fix

---

elpy-profile.el

Fix interpreter issue in elpy-profile.el

---

elpy.el

Fix empty lines disappearing when fixing code

---

.travis.yml
travis-evm-cask.sh

Add travis tests for python3.7.

Add support for python3.7

---

requirements.txt
requirements3.txt

Update python package requirements

Update python package requirements

---

elpy-shell.el

Follow discussion in #1550.
In some configurations (apparently MacOs with IPython), the interpreter displays series of `^G` when sending code to it. This issue appeared after PR #1534 was merged, and is strongly linked to function `elpy-shell-send-file`.
This PR just allow users to avoid the use of the faulty function (when `elpy-shell-echo-output` is nil) until we can find a proper solution.

Only gather last output evaluation when using output echoing

---

elpy/tests/support.py
elpy/tests/test_black.py
elpy/tests/test_jedibackend.py
elpy/tests/test_server.py

Add missing tests to increase coverage

Add missing tests to increase coverage

---

elpy-shell.el

Fix compiling error

---

elpy.el

Follow #1579.
Update warning messages in elpy-config

Update warning messages in elpy-config

---

elpy/blackutil.py
test/elpy-black-fix-code-test.el

Attempt to load black config from pyproject.toml

---

elpy-profile.el

Follow #1631 .
Add new profile visualiser options.

Add profile visualiser options

---

docs/ide.rst

Two minor typo/spelling fixes.

ide.rst: two minor typo/spelling fixes

---

docs/ide.rst

Documents alternatives added in #1638 in ide.rst.
Simple description extension.

ide.rst: Add documentation for #1638

---

elpy-shell.el
test/elpy-shell-echo-inputs-and-outputs-test.el

This simple two-line PR contributes to the effort to solve #1636.  Please see commit messages for more details.

Drop explicit setq to py2

---

elpy-rpc.el

Temporary fix in case `virtualenv` is not available

---

elpy-rpc.el
test/elpy-shell-kill-test.el
test/test-helper.el

Follow #1667.
Elpy is now asking the user permission before automatically installing packages from PyPI.

Ask user before installing any python packages

---

elpy-rpc.el

fix bug #1678

---

.travis.yml
travis-evm-cask.sh

Update test suite to test emacs26.1, emacs26.2, emacs26.3 and python3.7.

Support emacs26 and python3.7

---

README.rst

Removed an extra 's' in the README file.

Correct a typo

---

docs/customization_tips.rst
docs/ide.rst

Just some very minor fixes `lintian` complained about when I prepared 1.35.0 for Debian.  P.S. Our deadline for importing new features and new releases is early February.  After that I can only cherry pick fixes.

minor typo and style fixes

---

elpy.el

Small update to a minor typo in the elpy-modules variable customisation
Small update to a minor typo in the elpy-modules variable customisation
- [x ] Commits respect our [guidelines](../CONTRIBUTING.rst)

Minor typo
