jorgenschaefer/elpy

- elpy/impmagic.py
- elpy/server.py
If an exception occurs, report it to the user instead of always
saying "symbol index not yet ready"
Part of #479
> Importmagic: wrap index building in a try-except

- elpy/jedibackend.py
- elpy/tests/support.py
- elpy/tests/test_jedibackend.py
Reasoning: the Jedi docstring usually only includes the function name without full qualification. (And for modules, not even that.)
If you're fine with this change, I'll adapt the tests.
> Docstring: show what exact object the docstring is for

- elpy.el
Calling `elpy-flymake-next-error`, `elpy-flymake-previous-error`, or `elpy-flymake-show-error` when there is no errors in the buffer, produces the message "nil", which isn't very helpful. This patch silences it. Or maybe displaying a proper message would be better?
> Don't message "nil" when there is no error.

- elpy.el
there is nothing at https://github.com/jorgenschaefer/elpy/wiki/Keybindings
and I don't see any other page with keybinding info; probably better to not
have a link than to have a broken link.
> remove link to nonexistent documentation

- elpy.el
Adding "^" to the interactive spec of elpy-nav-forward-indent and
elpy-nav-backward-indent allows <C-left> and <C-right> to be used in
conjunction with shift to select blocks of text.
> Fix the interactive spec of elpy-nav-{for,back}ward-indent

- .travis.yml
- Makefile
- README.rst
- elpy-refactor.el
- elpy.el
- elpy/auto_pep8.py
- elpy/server.py
- elpy/tests/test_auto_pep8.py
- elpy/tests/test_server.py
- requirements.txt
- test/elpy-buffer--replace-block-test.el
Automatically format code to PEP8 style using autopep8.
If a region is selected format only that region else format entire buffer.
> Added support for autopep8

- docs/editing.rst
- elpy.el
- test/elpy-nav-indent-shift-left-test.el
- test/elpy-nav-indent-shift-right-test.el
If the first or last line are not fully selected, select them completely
then indent/dedent that region.
closes #644
> Normalize region before indent/dedent a region

- elpy.el
I have been using couple of hooks which   indent  code  automatically. Whenever i open elpy.el these 2   blocks will get indented  properly and while  staging it becomes  a problem as  i  have to stage entire file  and then  unstage   these 2 blocks. So just submitting this.
> Indent outdented code

- .gitignore
- .travis.yml
- README.rst
- elpy.el
- elpy/server.py
- elpy/tests/test_yapf.py
- elpy/yapfutil.py
- requirements.txt
- test/elpy-yapf-fix-code-test.el
[YAPF](https://github.com/google/yapf) is a more advanced python code formatter/pretty-printer than pep8. It works by first parsing the code into an AST, and then re-generating the source code by walking the tree, doing pretty print with the specified style config along the way.
In contrast, autopep8 only handles the part of the code that's inconsistent with PEP8.
> support yapf as another formatter

- docs/ide.rst
- elpy.el
Added yapf to elpy config.
Key binding(`C-c C-r y`) to call yapf formatter.
> Include yapf in elpy config

- elpy.el
Some days after installing elpy, I was wondering what had happened to my modeline. It was shorter, and several things I liked to have there where not displayed anymore (e.g. company, yas etc.). Company missing brought me to #618 , which fixed the problem for one module.
This PR provides a better fix: Let users choose if elpy interacts with the modeline at all by adding a new config variable "elpy-always-hide-modeline". It is true per default, so normal user should see no change.
> Add option to stop elpy fiddling with modeline

- snippets/python-mode/.yas-setup.el
Previously when using the yasnippet "super", it will always return
"(class, arg).method" which was the Py2 way of doing it. In Py3, you
could simply do "().method" and Python will understand.
Solves #771
> Return correct form of "super" depending on Python version

- elpy.el
When compiling elpy.el the byte compilers complains that insert-file is
intended for interactive use and insert-file-contents should be used
instead. As the function seems to have existed forever it seems pretty
safe to use.
> elpy.el: fix compiler warning

- .travis.yml
- elpy.el
- test/elpy-insert--pip-button-value-create-test.el
Currently "pip" is used to install missing modules in "elpy-config".
However, this may call the wrong version of pip, e.g. python3 often has
a pip executable "pip3" instead of "pip". This commit uses "python -m
pip" to call pip instead of the pip executable.
> Use "python -m pip" to install python modules instead of "pip".

- elpy.el
I use a lot of dedicated shells and I had some troubles with that (c.f. issue #690).
I modified `elpy-shell-get-or-create-process` so that `elpy-shell-send-region-or-buffer` behave correctly.
I also added a new option to force the use of dedicated shells for each buffers
(to avoid having to launch `run-python` manually each time).
I ran some test and it also work with different virtual environments for each buffer.
I can run some more tests if the idea seems interesting enough.
> Fix dedicated shells support 

- README.rst
As discussed here: https://github.com/jorgenschaefer/elpy/pull/976
rope and yapf removed - and it is all in one commit.
I could not squash the commits from the other PR because i made it online on GitHub so i did not have a fork :)
Anyways - are you happy with this?
> One-line python requirements install line added

- docs/ide.rst
- elpy.el
_"…setting the project root accordingly,
in order not to set the environnement variable DJANGO_SETTINGS_MODULE
for every project (but instead change of virtual env)."_
This PR does not change elpy's default behavior.
It adds a variable to tell elpy to run django tests with `manage.py` instead of `django-admin.py`. 
The thing is that we can't just set `elpy-test-django-runner-command` to our manage.py command because `elpy-test-at-point` needs to return the project root, not the library root.
Benefits: it allows a user to run tests quicker, with no venv or environment variable configuration. We just have to change of virtual env, which is easily done with other packages ([virtualenvwrapper.el](https://github.com/porterjamesj/virtualenvwrapper.el) and others). 
Because from my experience, …
> Option to run Django tests with manage.py

- Cask
- docs/ide.rst
- elpy-django.el
- elpy.el
- test/elpy-module-django-test.el
You can now parse through `manage.py` (If it is found, otherwise it
falls back to `django-admin.py`) for commands to run and emacs will
provide completion assistance.
Another function is to automatically start the development server
command, `runserver`, with default variables that are set to
`127.0.0.1`(for ip address) and `8000` (for port). Each Django project
has the ability of starting their own dev server.
One question I have regarding this is if we should also allow changing
the command for starting the development server, `runserver`? I know
other people like `runserver_plus` from the `django-extensions` module.
Commit also introduces a new dependency, `s`, for string
manipulation. Currently, it is only used on one line for trimming
whitespace. Should the commit introduce this new …
> Add basic Django support

- elpy.el
- elpy/impmagic.py
- test/elpy-importmagic--add-import-read-args-test.el
I use a lot a aliases while coding in python.
As importmagic handles aliases, it seems a good idea for the  `elpy-importmagic-*` functions to handle them as well.
- `elpy-importmagic-add-import` with non-nil `ask-for-alias` optional argument now ask for the wanted alias after choosing the import statement.
- `elpy-importmagic-fixup` now gathers unresolved module names (supposed to be aliases), ask for their real names and add import statements in consequence.
```python
HOME = r"/home/ben"
x = np.linspace(0, 1, 1000)
y = x**2
plt.figure()
plt.plot(x, y, marker=markers.TICKDOWN)
plt.title(time.time)
plt.show(block=False)
plt.savefig(join(HOME, "test-elpy/figure.svg"))
```
give, after `elpy-importmagic-fixup` and some prompting: 
```python
import time
from os.path import join
import numpy as …
```
> Add aliases to elpy importmagic

- docs/ide.rst
- elpy.el
- test/elpy-shell-kill-all-should-kill-all-shell-buffers.el
- test/elpy-shell-kill-all-should-kill-all-shells.el
- test/elpy-shell-kill-should-kill-shell-buffer.el
- test/elpy-shell-kill-should-kill-shell.el
With the use of dedicated shells, I end up having a lot of active python shells (potentially using a lot of memory...). 
As it can be time-consuming to search and kill each python shell, I wrote a function to do it automatically.
`elpy-shell-kill` : kill the current python shell (and the python shell buffer, if asked).
`elpy-shell-kill-all` : kill all the dedicated python shells (and their buffers, if asked).
> Add functions to kill shell(s)

- elpy.el
With a prefix arg, `elpy-importmagic-add-import` ask for an import alias.
> Add the possibility to use prefix arg in elpy-importmagic-add-import

- elpy-django.el
Emacs complains when byte-compiling this file
```
elpy-django.el:126:37:Warning: ‘beginning-of-buffer’ is for interactive use
only; use ‘(goto-char (point-min))’ instead.
elpy-django.el:117:87:Warning: ‘beginning-of-buffer’ is for interactive use
only; use ‘(goto-char (point-min))’ instead.
```
This PR should fix it.
> Fix compilation warnings

- elpy.el
Disabling completion can confuse users when happening silently. Addresses #1073 ("Warn" part).
> Warn if disabling completion

- elpy.el
The problem was, that the candidate names were concatenated with "prefix" and "suffix". The prefix of a case-insensitive candidate includes the wrong case, so company did not display the actual name correctly.
> Display case-insensitive company candidates correctly

- elpy.el
For some user (see #988), wild tabs seem to appear while sending code parts to python shell. 
This seems to be due (for me) to `indent-rigdly` in `elpy-shell--region-without-indentation`.
Using `untabify` after `indent-rigidly` fix the problem, but I don't think `indent-rigidly` is supposed to add tabs, so this just looks like a workaround...
> Fix apparition of tabs while removing indentation

- elpy.el
`elpy-shell-kill-all` run into an error  if a buffer have no name (`(buffer-name buffer)` returning `nil`).
This commit just add a preliminary check to ensure we work only with named buffer.
This bug is not easy to reproduce, so I don't know exactly what kind of buffer return no name...
> Fix no-name buffer error when using `elpy-shell-kill-all`

- elpy.el
> elpy-check: python-check-command is usually "epylint", not "pylint"

- elpy.el
(elpy-project-ignored-directories): extend the standard `vc-directory-exclusion-list'
(elpy-ffip-prune-patterns): extend `ffip-prune-patterns' using
`elpy-project-ignored-directories' and `completion-ignored-extensions'
(elpy-find-file): bind `ffip-prune-patterns' to `elpy-ffip-prune-patterns'
> fix a bug: elpy-find-file does not prune enough

- elpy-shell.el
Evaluating:
```Python 
print('Hello world')
print('Happy to be here')
```
now gives:
```Python
>>>
Hello world
Happy to be here
>>> |
```
(`|` is the cursor)
instead of:
```Python
>>> Hello world
Happy to be here
>>> |
```
While working (without outputs), the python shell will look like this:
```Python
>>>
|
```
instead of this:
```Python
>>> |
```
This gives an indication on the state of the python shell (working or waiting).
> Enhance shell reaction to code sending

- elpy.el
- elpy/jedibackend.py
- elpy/server.py
- elpy/tests/support.py
- elpy/tests/test_jedibackend.py
- elpy/tests/test_server.py
- test/elpy-goto-assignment-other-window-test.el
- test/elpy-goto-assignment-test.el
- test/elpy-rpc-get-assignment-test.el
Follow issue #1214.
Add `elpy-goto-assignment` function to benefit from the jedi `get_assignments` feature.
In this situation:
```Python
class TestClass(object):
def __init__(a, b):
self.a = a
self.b = b
testclass = TestClass(2, 4)
testcla|ss.a
```
`elpy-goto-definition` jumps to the class definition:
```Python
|class TestClass(object):
def __init__(a, b):
self.a = a
self.b = b
testclass = TestClass(2, 4)
testclass.a
```
while `elpy-goto-assignment` jumps to the variable assignment:
```Python
class TestClass(object):
def __init__(a, b):
self.a = a
self.b = b
|testclass = TestClass(2, 4)
testclass.a
```
> Add goto assignment function

- elpy-shell.el
There is a hard-coded delay of 3 seconds when sending code for the first time (using `elpy-shell-send-region-or-buffer` for example).
It can be annoying if ones needs to restart the python shell often.
Moreover, 3 seconds may not be enough for slow computer or heavily loaded python startups.
This fix instead detects the display of the first prompt ('>>>') in the python shell buffer.
I couldn't find a better way of doing this (e.g. catch a signal from the python shell ?).
@rgemulla: did I understand this delay correctly ?
> Avoid the delay of 3 seconds when sending code for the first time.

- NEWS.rst
- docs/ide.rst
A cut on the documentation for all the elpy-shell features that have been added recently, including the still open PR #1226.
> elpy-shell documentation

- docs/ide.rst
- elpy-shell.el
Fix issue #1178 (related to issue #1170).
New shells can now be started from the project root directory.
This feature is disabled by default to avoid confusing users and can be activated through the new option `elpy-shell-use-project-root`.
> Use project root as shell default directory

- elpy-shell.el
Follow discussion in #1100.
Automatically add the project root (git, svn, hg repo, python package or projectile project) to sys.path.
> Add project root to shell path

- elpy.el
I was reading the elpy documentation and I saw this: "If you use an Emacs version superior to 25, elpy will define the necessary backends for the xref package." I am on Emacs 25.2.2 but `M-.` was still bound to `elpy-goto-definition` instead of `xref-find-definitions`.
Looking at elpy.el, I can see that the check for `xref-find-definitions` is done with `boundp`. I am not very experienced with elisp, but from what I can gather `boundp` is for variables while `fboundp` is for functions. Changing these instances of `boundp` to `fboundp` seems to fix the issue for me.
If this is not the correct solution, or I have misunderstood how this functionality is supposed to work, please do let me know!
> fix overriding xref keys if xref is installed

- Cask
- elpy-django.el
When running `C-c C-x c (elpy-django-command)` I see the following:
`elpy-django--get-commands: Symbol’s function definition is void: -remove`
This change proposal appears to fix the error.
As with my other PR - I'm not very experienced with elisp so it's possible I'm missing something.
> fix void function call in elpy-django-command

- docs/ide.rst
- elpy.el
Some bugs were introduced by the last modification of the xref backend (#1258, my bad).
Notable `xref-goto-definition` and `xref-find-reference` now fail when the symbol assignment is in another file.
This PR fix those bugs.
(also fix the documentation for `xref-find-references`).
> Fix Xref reference mis-behavior

- .travis.yml
- elpy/tests/test_jedibackend.py
Add python3.6 and emacs25.3 to travis tests.
Also update a failing test (due to a change in json docstring in python3.6).
Should make #1243 obsolete.
> Update travis file to include last python and emacs versions

- elpy-shell.el
Fix Issue #1285.
When installing elpy from melpa on a clean emacs, 
compilation raise the following error: 
```
elpy-shell.el:977:1:Error: Symbol's function definition is void: string-remove-suffix
```
It is fixed by adding the dependency to `subr-x` in `elpy-shell.el`.
Still, I thought that requiring `subr-x` in `elpy.el` would be enough, 
any ideas why it is not the case ?
> Add missing dependency, fix #1285

- elpy-django.el
- elpy-refactor.el
- elpy-shell.el
- elpy.el
Fix some compilation warnings, mainly due to:
- obsolete command
- use of interactive-only commands
- unused variables
> Fix some compilation warnings

- elpy.el
Following #1275.
Presence of yapf and autopep8 is now checked by verifying the presence of the modules in the RPC instead of verifying the presence of their binaries.
Additionally, is there a good reason for the syntax checker to be specified as an executable instead of as a module ?
Would it not be more coherent to use the module, as for yapf, autopep8, ...
> Check for yapf and autopep8 modules instead of executables

- docs/extending.rst
The proper way to run Elpy test suite is only documented in `CONTRIBUTING.rst`, and no available in ReadTheDocs.
Added a paragraph about running Elpy tests in documentation.
> Add documentation about running Elpy tests properly

- docs/ide.rst
- elpy-shell.el
- test/elpy-shell-kill-all-should-kill-all-shell-buffers.el
- test/elpy-shell-kill-all-should-kill-all-shells.el
- test/elpy-shell-set-local-shell-test.el
- test/elpy-shell-toggle-dedicated-shell-test.el
Apparently Elpy users have a wide variety of workflows that necessitate different relations between python buffers and interactive shells (see PR #839 and issues #1100 and #1197).
This is an attempt to allow all those different workflows while keeping the code simple.
This PR defines a new option `elpy-shell-code-sending-strategy` which can be used to control to which python shell the code should be sent. 
Available options are:
- **on-shell**: the default behavior of elpy. everything is sent to a main python shell.
- **dedicated-shells**: the old behavior of elpy when `elpy-dedicated-shells` was non-nil. Each buffer send its code to a dedicated python shell. Functionality introduced by PR #839.
- **manual-switching**: the code is sent to a main python shell for all buffers, but you can …
> Allow better code sending to shell

- test/test-helper.el
Before this change, PYTHONPATH was completely overriden to take only
the directory of Elpy's root directory. This caused problems for
platforms such as Guix which uses PYTHONPATH to provide the required
test dependencies.
> test: Honor existing PYTHONPATH when running tests.

- elpy-django.el
- elpy.el
- test/elpy-module-django-test.el
- test/elpy-test-django-runner-test.el
The user can now add test runners into a list if they need to put the correct format
Not sure if this is the right approach but some people do use custom test runners 
Should also probably add this in the docs if it's approved
> Allow different Django Test Runners

- elpy.el
Follow issue #1297.
`company-sort-by-occurence` does not work in inferior-python-mode and can prevent company from showing up (see company-mode/company-mode#759).
As proposed in company-mode/company-mode#759, this PR just make sure `company-sort-by-occurence` is deactivated in `inferior-python-mode`.
This workaround will have to be removed when(if) the issue disappear.
> Fix company bug when using completion in the interpreter

- docs/ide.rst
- elpy-django.el
- test/elpy-module-django-test.el
- test/elpy-test-django-runner-test.el
Instead of recalculating which django command to use, just use the
variable that holds that information already. Also, move test args to
a single place instead of having one for django-admin.py and another
for manage.py
> Use elpy-django-command more often

- docs/elispdomain.py
- docs/ide.rst
Hi Jorgen,
The first of these trivial patches is needed to build documentation on a python3-only system (release goal for Debian 10/Buster).  The second is fairly self-evident I think :-)
Cheers,
Nicholas
> Minor changes needed for Debian

- docs/ide.rst
- elpy.el
- test/elpy-doc--autodoc-test.el
- test/elpy-module-autodoc-test.el
Following feature request #1276.
This PR adds the automatic update of the documentation buffer based on the symbol at point.
Documentation is also updated in company, based on the currently selected candidate.
To avoid documentation poping up unexpectedly, the documentation is only updated when the documentation buffer is visible (i.e. associated to a window).
The delay before which updating the documentation is controlled by the option `elpy-autodoc-delay`, that can be set to `nil` to deactivate the feature.
> Auto-update of the documentation buffer

- elpy-django.el
Looks like somewhere along the way, this function was removed :P 
Related to #1200
> Add missing function back

- elpy.el
Following PR #1320.
This avoid annoying warnings appearing in `elpy-config` for python >= 3.2.
> Properly close ServerProxy ressource

- .github/issue_template.md
- .github/pull_request_template.md
There is a significant potion of the issues that take times to resolve due to lack of information.
In the hope that this will make the process easier, I added an issue template to indicate to the users what kind of information we need.
I also added a PR template, to be sure no one forget about tests, documentation updates and changelog updates (which I forget myself quite often...).
> Add github PR and issue templates

- elpy-shell.el
- test/elpy-shell-get-or-create-process-test.el
Following issue #1333.
Elpy now raises an error if the wanted interpreter (set by `python-shell-interpreter`) is not available within the current virtual environnement.
This avoid Elpy to just fall back to the system interpreter binaries, outside of the virtual environment, without the user noticing.
> Raise an error if the interpreter is not in the current virtualenv

- elpy.el
Fix issue #1345:
`elpy-format-code` raise an error when the script is outside a project.
> Prevent 'expand-file-name' from erroring when project-root is nil

- elpy-shell.el
The name of the dedicated python shells are now using the buffer name
without extension, for example `*Python[test]*` instead of `*Python[test.py]*`.
This avoid conflicts with the way python.el handles dedicated shells
(see #1328).
> Use new convention for python shell name

- elpy.el
flymake-err-info is removed without alias in flymake emacs >= 26.
Related discussions:
https://github.com/jorgenschaefer/elpy/issues/1272
https://github.com/jorgenschaefer/elpy/issues/1357
http://lists.gnu.org/archive/html/bug-gnu-emacs/2018-04/msg00985.html
Hello Elpy hackers, lets prepare for emacs 26 :)
Wrap current code in the first of two cond clauses, add new check for emacs >= 26 in the second clause.
This is a possible refinement of https://github.com/jorgenschaefer/elpy/pull/1360 which I think might fail for emacs < 26 by returning nil. I didn't add or fix any tests for now because I don't feel ready for it, the test frame work is new to me. But tests will need to be updated too I …
> elpy.el: prepare for flymake in emacs >= 26

- docs/ide.rst
Quick fix for the documentation on project shells.
The proposed way to use a shell per project was not working.
> Fix misleading doc on project shells

- elpy-shell.el
- elpy.el
- test/elpy-shell-get-or-create-process-test.el
Currently, if the wanted interpreter binaries are not in the active virtualenv, `elpy-shell-get-or-create-process` fails with an error.
Some users complained about the impossibility of using the system python binaries from inside a virtualenv (#1370).
This PR removes the error, and adds an entry in `elpy-config` to warn users, in case they just forgot to install their interpreter:
```
Elpy Configuration
Virtualenv........: dummy (/home/glaunay/.virtualenvs/dummy)
RPC Python........: 3.6.5 (/home/glaunay/.virtualenvs/dummy/bin/python3)
Interactive Python: ipython (/usr/bin/ipython)
Emacs.............: 25.3.1
Elpy..............: 1.20.0
Jedi..............: 0.12.0
Rope..............: Not found (0.10.7 available)
Autopep8..........: Not found (1.3.5 available)
Yapf..............: Not found …
```
> Replace error by warning when interpreter is not in the virtualenv

- elpy.el
- test/elpy-xref--backend-test.el
Fix issue #1379.
Modifications in xref in Emacs 26 highlighted an issue with xref implementation in elpy:
if the rpc is not started for the current buffer, elpy xref backend is not activated and the default backend (etags) is used instead.
This PR makes sure that Elpy starts the rpc before checking if elpy xref should be activated or not.
Also add some tests.
> Fix #1379: Be sure to start the rpc before checking for jedi

- .travis.yml
- NEWS.rst
- docs/ide.rst
- elpy.el
- elpy/blackutil.py
- elpy/server.py
- elpy/tests/test_black.py
- requirements3.txt
- test/elpy-black-fix-code-test.el
Add [Black](https://github.com/ambv/black) auto formater support to elpy.
Follow issue #1377.
Try it with `M-x elpy-black-fix-code`.
@jorgenschaefer It was a pretty straightforward implementation, mainly copy and paste from yapf implementation.
Not much work involved, so we can perfectly discard this PR if you think it involve adding too much complexity (and support work in the futur).
> Add black autoformatter

- elpy/blackutil.py
- test/elpy-black-fix-code-test.el
Fix #1384.
Black raises an error when the code is already formatted correctly.
Elpy now ignore this error, instead or raising an "Elpy error".
Also added some tests to cover this.
> Fix error when try to blacken already formatted code

- elpy.el
`elpy-eldoc-documentation` expects `elpy-flymake-error-at-point` to return nil when no flymake errors at point.
This was not the case for emacs >= 26, for which `elpy-flymake-error-at-point` return an empty string.
This empty string is printed in the minibuffer instead of the desired calltip.
Linked to #1388.
> Prevent flymake to overwrite calltip

- elpy.el
Follow issue #1389.
When eldoc and company modules are enable, and company activated, the two modules compete for the minibuffer message.
This create flickering and changing minibuffer message.
This PR deactivate company meta frontend, and indicate to eldoc to reprint message after company functions to avoid those issues.
> Prevent interferences between eldoc and company

- elpy.el
- test/elpy-flymake-next-error-test.el
- test/elpy-module-flymake-test.el
Following issue #1406.
For Emacs > 26.1, Elpy now uses `elpy-syntax-check-command` to determine which syntax checker to use, instead of always using "flake8".
Also, the syntax checker is now set locally in elpy buffers.
> Use `elpy-syntax-check-command` for emacs > 26.1

- elpy.el
Following issue #1410 (see details there).
> Silent FutureWarning preventing correct parsing for elpy-config

- elpy.el
- test/elpy-eldoc-documentation-test.el
Follow #1416: 
- Elpy eldoc messages are now truncated to fit in the minibuffer if `eldoc-echo-area-use-multiline-p` is `nil`.
- Eldoc messages are now shorter, removing the useless `param ` strings returned by the jedi backend.
> Male eldoc message shorter and truncate them if too long

- elpy-shell.el
Follow discussion in #1424.
When `elpy-shell-echo-output` is `t`, the output is always echoed in the minibuffer, even when inputs are directly entered into the shell buffer.
This is due to the variable `elpy-shell--capture-output`, that is set to `t` by commands needing to echo the output, but never set back to `nil`.
Consequently, the output filter grabs and echoes all outputs.
This is fixed here by reseting `elpy-shell--capture-output` to `nil` after having echoed an output.
WIP: need to be tested properly.
> Fix echoing output in the minibuffer

- elpy.el
Just additional precautions, should not change anything
if the rest of xref implementation work fine.
> Minor bugfix in xref

- elpy.el
- test/elpy-xref--get-completion-table-test.el
- test/elpy-xref--identifier-at-point-test.el
Follow #1426.
In xref, do not check for candidate assignments anymore.
This feature was present to prevents redondant candidates,
but is too slow to be decently usable.
> Make xref faster

- elpy.el
Follow issue #1422.
From emacs 26.1, flymake modeline indicator provides useful informations.
It is no longer required to hide it.
> Do not remove flymake from the modeline for emacs > 26.1

- elpy.el
- elpy/jedibackend.py
- elpy/tests/test_jedibackend.py
Follow #1435.
Stripping of the `param` prefixes are now done in `jedibackend.py` instead of in `elpy.el`.
This fixes the error described in #1435.
> Strip jedi prefix in python instead of in elisp

- test/elpy-config-test.el
- test/elpy-insert--pip-button-value-create-test.el
I believe this is closely related to #1274, and further changes may be required, because this patch only affects the self tests.  This patch is needed to prevent the following failing tests when building on a Debian 10 (buster, though technically I'm building for sid) where /usr/bin/python3 is the only Python.
```
2 unexpected results:
FAILED  elpy-config-should-show-flake8-pip-button-when-no-syntax-checker-available
FAILED  elpy-insert--pip-button-value-create-should-use-pip
```
Here is how I added preliminary configuration to default to system-installed Python 3 in the Debian (and inherently the future Ubuntu) package:
https://salsa.debian.org/emacsen-team/elpy/blob/master/debian/debian-config.el
https://salsa.debian.org/emacsen-team/elpy/blob/master/debian/elpa-test
> Allow pip-related tests to pass with python3 or /usr/bin/python3

- test/elpy-config-test.el
Follow #1292  (an old one).
Minor fix regarding elpy-config test.
> Fix elpy config test

- elpy.el
python.el sometimes raises an error when asked for completion.
This fix ensures that the error is ignored and does not interrupt the current
completion.
> Fix gathering completion candidates from interpreter

- elpy.el
Use a simpler way to access the completion candidates from the shell (offered by python.el).
This may fix the problems observed in #1453 (or not).
> Use a simpler way to access python.el completion candidates

- elpy.el
Completion coming from rpc are intended to merged with completions from python.el.
`python-completion-complete-at-point` returns nil when there is no python shell
process, `elpy-company--add-interpreter-completions-candidates` returns nil in
this case and this shadows completion coming from rpc.
> fix completion with no python process

- elpy.el
If the shell prompt is not available, trying to gather completion candidates from the python shell will result in emacs hanging (waiting for the shell to be available).
To avoid freezing emacs, elpy now checks for prompt availability before trying to fetch completion candidates.
> Check for prompt availability before gathering candidates from shell

- elpy.el
Following #1425.
In the python shell, completion should now be triggered for
variable with one character-length names.
> Make sure completion is triggered for one characters variables

- elpy.el
With asyncio, a def may be preceded by the keyword 'async'.  This makes
elpy-occur-definitions work for these methods.
Apologies I have not completed the checklist - this is just a regex edit.  Do with this what you will...
> make elpy-occur-definitions work for async methods

- elpy-django.el
- test/elpy-module-django-test.el
Check for correctness of DJANGO_SETTINGS_MODULE env var was made by ensuring
that python importing wasn't generating any output/error.
This is not safe since during import the settings module can cause logging and
other forms of output.
Checking that python exits 0 status code is more robust and semantically
correct.
> Django check settings module by testing exit code instead of output

- docs/elispdomain.py
- docs/extending.rst
Following #1470.
Will remove warnings in sphinx (linked to sphinx issue [#2673](https://github.com/sphinx-doc/sphinx/issues/2673)).
Fix is inspired from javasphinx fix (commit [67e175](https://github.com/bronto/javasphinx/commit/67e1756d6edcb8c54d89ca5e567cef17db1be453)) and will ne need to drop sphinx < 1.4 support.
> Handle sphinx warnings linked to indexnode

- elpy-django.el
- test/elpy-module-django-test.el
Keys in associative list elpy-django-test-runner-formats are now interpreted as regular expression.
This allows more flexibility.
> django test: elpy-django-test-runner-formats used as regexes

- elpy.el
- elpy/jedibackend.py
- elpy/server.py
- test/elpy-eldoc-documentation-test.el
Add the possibility to display a oneline docstring for the symbol at point in eldoc.
Works for modules, classes and functions.
Here is an example of how eldoc works with this feature:
The option `elpy-eldoc-info` replaces `elpy-eldoc-show-current-function` to allow to customize this feature.
> Eldoc docstring

- docs/ide.rst
Removed doc for elpy-use-ipython, elpy-use-cpython.
Also moved refs to ipython so they weren't lost.
> Removed doc of obsolete funs.

- elpy.el
Follow #1493.
Until now, Elpy only accepts `elpy-syntax-check-command` to be single a command (`flake8` or `pyflakes` for example).
With this PR, it is now possible to specify arguments, like:
- `(setq elpy-syntax-check-command "flake8 --config=~/.flake8/flakerc")` to specify a given configuration file, or
- `(setq elpy-syntax-check-command "flake8 --ignore=E402,E401")`  to ignore some errors and warnings.
> Allow to specify arguments to syntax checker

- elpy-django.el
- test/elpy-module-django-test.el
Detecting the django runner before running a test requires now two execute two python processes.
On large projects this can be quite slow (in the order of seconds also in a fast computer).
This patch catches the runner for a (project, django settings) combination, speeding tests
execution
> django tests: add cache for runner discovery

- docs/ide.rst
- elpy-shell.el
- test/elpy-shell-echo-inputs-and-outputs-test.el
- test/elpy-shell-send-statement-test.el
Follow second discussion in #1505.
For this given code:
```Python
def foo():
1+1
while True:
2+2   # <- cursor here
```
Following commit #1520, using `elpy-shell-send-statement-and-step` would lead to the following result in the shell buffer:
```python
In [7]: if True:
...: 
...: 
...: 
...: 
...:             2+2
In [8]: 
```
which is quite ugly and doesn't echo the excepted output value `4`.
Filtering the `if True:` and removing the indentation on the region lead to the much nicer echo.
Slightly modifying the function `elpy-shell-send-file` allows to get the output back
```Python
In [7]: 2+2  
Out[7]: 4     
In [8]: 
```
> Nicer display of inputs echoing

- elpy-shell.el
When `elpy-shell-echo-output` is non-nil and the code sent to the interpreter raise an exception, elpy tries to display the exception description in the echo area, which is annoying.
This PR fixes this.
> Don't echo outputs when exception occurs

- elpy.el
For Emacs > 26.1, all flake8 notices are labeled as error.
This PR labels error codes beginning by "W" as warnings.
> Note warnings as such for emacs > 26.1

- elpy-shell.el
Follow and fix #1542.
Elpy should now be able to detect python version for any implementations.
> More robust python version detection

- elpy.el
For some reason melpa stable doesn't have a version 1.11.0 of `s`.
Bump version so that it won't break in the future
- [ x ] Commits respect our [guidelines](../CONTRIBUTING.rst)
- [ x ] Tests are passing properly (see [here](https://elpy.readthedocs.io/en/latest/extending.html#running-tests) on how to run Elpy's tests)
> Bump version of library 's'

- elpy-shell.el
- test/elpy-shell-echo-inputs-and-outputs-test.el
Following 464e9f8c26f9a4b9332a4bcae3ff3ba06b250166, sending code to the shell has been shown to be way slower that before for ipython.
This is expected to be due to `elpy-shell-get-python-version`, quite slow for ipython.
This PR fix this by avoiding the use of this function.
> Fix code evaluation slowdown following commit 464e9f8

- elpy-shell.el
Follow #1549.
Add a (useful) warning when the python interpreter is not a valid python binary.
May not be completely useful for emacs 26, that already display a useful message.
> Add warning when python binaries cannot be found

- elpy/blackutil.py
Arguments that need to be passed to black for code formatting changed with version 19.
This PR add support for black 19.
> Fix support for black > 19

- elpy.el
- test/elpy-project-find-python-root-test.el
This simple change adds `pyproject.toml` to the list of filenames `elpy-project-find-python-root` looks for, to support projects that use `pyproject.toml` instead of `setup.py` or `setup.cfg`
> Add pyproject.toml to python project root finder

- elpy/blackutil.py
Add support for black > 19.
Support was broken because black syntax changed between black 18 and black 19.
> Add support for black > 19

- elpy-shell.el
Follow #1550.
Thanks to @ConnorNelson for finding this workaround.
> Temporary workaround to avoid appearance of `^G` on MacOs

- elpy-shell.el
Reverts jorgenschaefer/elpy#1562.
Does not seem to fix MacOS issues...
> Revert "Temporary workaround to avoid appearance of `^G` on MacOs"

- elpy.el
Replace `xmlrpclib` with `urllib2`.
There has been issues with xmlrpclib being slow when doing
`elpy-config`. Luckily, with the new version of pypi, there are some
new json API's that can be used. These changes reflect that.
I noticed that SSL in Python 3.6+ is an issue on Mac OS when using urllib. (See here: https://stackoverflow.com/a/42334357/2178312)
Something to be aware of when users come to elpy about this but then again, this isn't elpy specific issue 🤷‍♂️ 
- [N/A] Tests has been added to cover the change
- [N/A] The documentation has been updated
> Replace xmlrpclib with urllib2

- elpy.el
Related to #1521.
Elpy failed to parse JSON when `json-encoding-pretty-print` is set to `t`.
This PR ensures that this variable is set to `nil` when Elpy need to parse or encode JSON.
> Add safeguard for json parsing

- elpy-shell.el
Follow #1591.
When using `elpy-send-statement` on the last buffer line, Elpy tries to send long empty strings to the shell.
This result in the display of a lot of shell prompt.
This PR fixes this behaviour.
> Don't send statement when there is no statement to send

- docs/index.rst
- docs/quickstart.rst
Add a simple and straightforward "quickstart" section to the documentation.
This is intended for new users so they can start using Elpy without having to read the whole documentation.
> Add a "quickstart" section to the documentation

- elpy.el
Related to #1596.
If Elpy is enabled (with `elpy-enable`) while some python files are already open, `elpy-mode` will not be activated in them (before `elpy-mode` uses `python-mode-hook`).
This PR makes sure that elpy-mode is properly activated in already existing python buffer.
> Enable elpy-mode in python buffer when enabling Elpy

- Cask
- elpy/jedibackend.py
- elpy/tests/support.py
- elpy/tests/test_jedibackend.py
- requirements-dev.txt
- requirements.txt
- requirements3.txt
Travis tests seems to be broken (see PR #1611) because Elpy depedencies are out-of-date.
This PR is just a dependencies update.
> Update Elpy dependencies

- elpy/blackutil.py
- elpy/tests/test_black.py
- test/elpy-black-fix-code-test.el
This is my attempt to fix #1610. The issue is using `configparser`, which doesn't handle multiline strings that's allowed in TOML files.
I added a multiline setting to the existing pyproject test to help validate my change. I'm using the `toml` library to do the parsing, which is installed as a dependency of `black`.
Please let me know if there's anything I should change!
> Use the toml library to parse pyproject.toml.

- elpy/tests/test_jedibackend.py
Calltips and docstring format changed with jedi 14.
This PR fixes the tests following those changes.
> Fix tests following changes in calltip format in jedi

- elpy.el
I noticed that elpy removes `company-echo-metadata-frontend` from the global value of `company-frontends`. I believe this is caused by trying to disable `company-echo-metadata-frontend` to avoid conflicting with eldoc, but `delq` modifies the references to cons cells, thus even though `company-frontends` is made local, its global value still gets affected.
This PR fixes that.
> Fixed bug where elpy modifies company-frontends global value

- docs/ide.rst
- elpy.el
Just a minor grammar update to fix "allows to" in a way that reads smoothly.
> elpy-get-info-from-shell grammar fixes

- snippets/python-mode/pdb
Follow #1643. 
Replace the snippet triggered by `pdb` from `import pdb; pdb.set_trace()` to `__import__("pdb").set_trace()`.
The new value has the advantage of being a oneliner and of being less confusing for automatic formaters.
> Replace pdb snippet with a oneliner

- elpy.el
- test/elpy-black-fix-code-test.el
- test/elpy-rpc--find-buffer-test.el
- test/elpy-rpc--open-test.el
- test/elpy-test-discover-runner-test.el
Follow #1636 
Remove hard-written occurrences of "python" from Elpy's code in favor of `python-shell-interpreter`.
This will avoid test failure and weird behaviour when using python binaries with exotic names.
> Removed hard-written occurences of "python"

- docs/ide.rst
- elpy.el
Follow # 1635.
Change elpy-pdb keybindings, from `C-c C-g` to `C-c C-u`.
> Avoid C-g in elpy-pdb keybinding

- elpy.el
- test/elpy-config--get-config-test.el
Follow #1472.
This PR reformats a bit the elpy config menu and make some elements clickable to ease the customisation of some important variables.
> Make `elpy-config` elements clickable

- elpy-rpc.el
I experienced a bug where the elpy-rpc was installed in
"~/\~/.pyenv/versions/elpy-rpc-venv".
This fixes it at no cost.
Fixed a bug in elpy-rpc.el that generated the elpy-rpc with an unexpanded file name.
> Added Expand-file-name to elpy-rpc-venv

- elpy-django.el
- elpy.el
- test/elpy-project-find-django-root-test.el
Follow #1654. 
Elpy is currently using projectile files (`.projectile`), python package files (`setup.py`, `pyproject.toml`, ...) and vcs files (`.git`, `.svn`, `.hg`, ...) to detect where the project root is.
This PR add `manage.py` and `django-admin.py` to the list of detected files when `django-mode` is activated. This can be useful for Django users that do not use projectile and vcs.
> Make sure Django project roots are detected properly

- docs/concepts.rst
- elpy-rpc.el
- elpy.el
- test/elpy-config--get-config-test.el
- test/elpy-rpc--open-test.el
- test/elpy-rpc-get-venv-test.el
- test/elpy-rpc-get-virtualenv-path-test.el
- test/elpy-with-rpc-venv-activated-test.el
Follow #1652.  
PR #1548 broke some users workflow by enforcing the use of a given virtualenv for Elpy's RPC.
This doesn't allow users to have full control of the package version they want to be installed in the RPC.
This PR introduces a new option `elpy-rpc-venv-path` that allows customizing the virtualenv used by the RPC.
- I want the last version of the RPC packages: do nothing
- I want the RPC to use a specific virtualenv where I can control the packages version: `(setq elpy-rpc-venv-path "/path/to/the/RPC/venv")`
- I want the RPC to use the current virtualenv: `(setq elpy-rpc-venv-path (lambda () pyvenv-virtual-env))`
> Add a variable to customize Elpy's RPC path

- elpy-django.el
- requirements-rpc.txt
- test/elpy-module-django-test.el
Follow #1672.
At the moment, Elpy is able to run Django commands (shell, createsuperuser, dbshell, ...) but does it with `compile` which does not allow to interact with the resulting buffers.
This PR switches from `compile` to `make-comint` to allow users interaction (using the shell, using the database shell, inputting passwords, ...).
> Allow to interact with buffers resulting from `elpy-django-cmd`

- docs/concepts.rst
- docs/ide.rst
- elpy-shell.el
- test/elpy-shell-starting-directory-test.el
Follow #1306.
Make the Python shell starting directory customisable.
> Make Python shell starting directory customizable

- elpy-rpc.el
- elpy.el
- test/elpy-rpc-get-virtualenv-path-test.el
When `elpy-rpc-virtualenv-path` is set to `'global` and Emacs is started from a virtualenv, Elpy's RPC is at the moment using this last virtualenv, instead os using the system binaries.
WIth this PR, Elpy has a more reliable way of finding the system python binaries that fix this issue.
> More reliable way of finding the system python binaries

- docs/concepts.rst
- elpy-rpc.el
- elpy.el
- test/elpy-rpc-get-virtualenv-path-test.el
Follow #1673.
For the option `elpy-rpc-virtualenv-path`, the name `'system` makes more sens than `'global` to refer to the use of the system python binaries (see [this](https://github.com/jorgenschaefer/elpy/issues/1673#issuecomment-537289523) comment).
This PR just change that.
> Use more sensible name for `elpy-rpc-virtualenv-path` option

- docs/extending.rst
- elpy-django.el
- elpy-profile.el
- elpy-refactor.el
- elpy-rpc.el
- elpy-shell.el
- elpy.el
- snippets/python-mode/.yas-setup.el
- test/elpy-config--get-config-test.el
- test/elpy-rpc--open-test.el
- test/elpy-rpc-get-venv-test.el
- test/elpy-rpc-get-virtualenv-path-test.el
- test/elpy-shell-echo-inputs-and-outputs-test.el
- test/elpy-with-rpc-venv-activated-test.el
- test/test-helper.el
Follow #1673.
This allows to run Elpy test suite on system that cannot use virtual environments.
This is notably helpful for the Debian package
> Allow to run tests without using virtualenvs

- Cask
- elpy-rpc.el
- elpy/blackutil.py
- test/elpy-rpc-get-virtualenv-path-test.el
- test/elpy-rpc-reinstall-venv-test.el
- test/test-helper.el
Follow #1674.
When Elpy's RPC virtualenv is created with an virtualenv activated, the resulting RPC virtualenv was bound to the active virtualenv and (for some reasons) missing pip and some other dependencies.
This PR make sure the RPC virtualenv is created from the system environment.
> Be sure the rpc virtualenv is create from the system environment

- docs/ide.rst
- elpy-shell.el
- test/elpy-shell-send-defun-test.el
Follow #1704.
At the moment, `elpy-shell-send-statement` and `elpy-shell-send-defun` do not send the decorators of decorated functions.
This PR make those functions aware of decorators so that they are properly send to the shell with their function definition.
> Make Elpy aware of decorators

- elpy-shell.el
This fixes two problems when sending regions to the python interpreter via the `elpy-shell-send-region` functions.
Consider input
```
1 ; 2 ; 3
```
Mark only ```2``` and call `elpy-shell-send-region`.
Before patch:
- ```1; 2``` was sent to the interpreter.
- ```Sent: 1; 2; 3``` was shown in the echo area.
After patch:
- ```2``` is sent to the interpreter
- ```Sent: 2``` is shown in the echo area.
I documented details and fix of this problem in the PR's code. The patch also works correctly when multiline statements are selected.
> Bugfix for sending regions to shell

- elpy-rpc.el
- elpy.el
Add additional warnings when Elpy failed to install the rpc virtualenv properly, or when pip is not properly installed in the rpc virtualenv (see #1674 for example).
> Add warnings when the rpc venv is not properly installed

- docs/ide.rst
- elpy-shell.el
- elpy.el
- test/elpy-shell-add-to-shell-history-test.el
- test/elpy-shell-echo-inputs-and-outputs-test.el
Follow #1430.
When sending a statement/region/defun/group/codecell, Elpy is now adding the sent string to the comint history. 
This allows to get those inputs back from the shell with `comint-previous-input` and similar.
> Add string sent by Elpy to the comint history

- docs/concepts.rst
- elpy-rpc.el
Follow #1713 .
The way the RPC virtualenv is created has been modified lately in #1699.
Elpy now try to use the system python interpreter to create the virtualenv.
It has been done for two reasons:
- virtualenvs created by `venv` keep a link with the environment they have been created from, which is notably a problem when using pip in them.
- the python interpreters for the RPC and the interactive shells don't have to be the same, so most of the time, it doesn't really matters which interpreter is used for the RPC.
This PR just update the documentation of `elpy-rpc-python-command` to reflect those changes.
> Update the documentation on `elpy-rpc-python-command`

- docs/ide.rst
- elpy.el
- test/elpy-folding-fold-all-comments-test.el
- test/elpy-folding-fold-all-docstrings-test.el
- test/elpy-folding-fold-blocks-test.el
- test/elpy-folding-fold-comments-test.el
- test/elpy-folding-fold-docstrings-test.el
- test/elpy-folding-fold-leafs-test.el
- test/elpy-folding-fold-on-click-test.el
- test/elpy-folding-should-mark-foldable-lines-test.el
- test/test-helper.el
Follow (old) feature request #240.
This is an attempt to get nice folding functionalities in Elpy.
It is currently based on `hs-minor-mode` and heavily inspired from [hideshowvis](https://www.emacswiki.org/emacs/hideshowvis.el).
Any idea is welcome.
> WIP: Getting folding right in Elpy

- elpy.el
Follow #1719.
Just display a warning when jedi is not installed and the user is trying to use a function that needs it.
This will redirect users to `elpy-config`, that allows to install jedi.
> Add warning when jedi not installed

- elpy/jedibackend.py
> Fix simple typo: beggining -> beginning

- elpy.el
elpy-folding--mark-foldable-lines was disrupting editing activities, like query replace, because it failed to save match data. This PR fixes that, wrapping the effective body of the function in save-match-data. I also wrapped resulting long lines.
> Make after-change-function save match data.

- elpy.el
Follow #1740 (thanks for @yoricksijsling for the investigation).
Currently, in `elpy-config`, Elpy tries to install flake8 in the rpc venv.
This PR fixes this and Elpy now properly installs flake8 in the current environment.
> Install flake8 in the current env instead of the rpc venv

- elpy.el
Fix a fatal typo in elpy-format-code
> Fix a fatal typo in elpy-format-code

- elpy-rpc.el
- elpy.el
- elpy/jedibackend.py
- elpy/server.py
- elpy/tests/support.py
- elpy/tests/test_server.py
- test/elpy-eldoc-documentation-test.el
Make eldoc display faster by avoiding multiple calls to the RPC.
Also enhance a bit the kind of information eldoc displays:
- Avoid displaying infos about basic builtins  
- In case we can display a calltip and a function at the same time, favour the function if the doc is available.
> Make eldoc faster (and slightly smarter)

- elpy.el
Fix for #1788 
Instead of unconditionally removing ElDoc from modeline, use `elpy-modules-remove-modeline-lighter` to respect user's setting when `elpy-remove-modeline-lighter` set to `nil`.
6 unexpected failures, but they are not related to the proposed changes.
> Make removal ElDoc from modeline conditional #1788

- elpy.el
- test/elpy-folding-fold-all-comments-test.el
- test/elpy-folding-fold-all-docstrings-test.el
- test/elpy-folding-fold-blocks-test.el
- test/elpy-folding-fold-comments-test.el
- test/elpy-folding-fold-docstrings-test.el
- test/elpy-folding-fold-leafs-test.el
- test/elpy-folding-fold-on-click-test.el
- test/elpy-folding-should-mark-foldable-lines-test.el
- test/elpy-mode-test.el
- test/elpy-open-and-indent-line-above-test.el
- test/elpy-open-and-indent-line-below-test.el
Elpy needs to be activated with `(elpy-enable)`.
Starting directly `elpy-mode` (which is more intuitive) will only partially work.
This PR adds a warning message in case a user start directly `elpy-mode` without having enabled it.
> Add warning when Elpy not properly enabled

- elpy.el
- test/elpy-eldoc-documentation-test.el
This UNTESTED commit should hint at how to fix the issue without
resorting to `eldoc-docstring-format-sym-doc', which is gone in Emacs
28 (ElDoc 1.1.0).
Beyond the ideas delineated in this commit, the new ElDoc protocol
would also easily obviate the need to have "flymake-specific" ElDoc
code in ElPy (this is now default in stock Flymake), as well as being
forced to choose between different types of ElPy docstrings.
* elpy.el (elpy-module-eldoc): Add to eldoc-documentation-functions.
(elpy-eldoc-documentation): Rework to support
eldoc-documentation-functions.
> Fix #1823: support newer eldoc protocol

- docs/elispdomain.py
Closes: #1816
I decided to try the naïve approach, and it appears to work.  There may be dependencies on other deprecated functions, but I haven't yet learned how to lint Sphinx docs.  I've tested with Sphinx 1.8.4, and am currently setting up a test with 3.1.1, and results will follow shortly.
> docs: migrate away from functions removed in Sphinx 3.0

- docs/ide.rst
- elpy.el
- test/elpy-format-code-test.el
This PR allow the user to select the autoformatter used by `elpy-format-code`.
Until now, Elpy was using the first one it could found.
> Allow to select autoformatter

- elpy-shell.el
- test/elpy-module-yasnippet-test.el
- test/elpy-shell-send-file-test.el
Too long of a string causes the string to be sent in batches
due to the limit of the input buffer size of processes
on some machines.
https://github.com/jorgenschaefer/elpy/issues/1550
This reverts commit 740b0a046f8b1750d8fccd8e578df67efc04e927
and introduces an alternative fix for the performance
enhancement that commit introduced.
The notes and repro details below are copy/pasted from the 1550 issue thread. 
I can recreate this on-demand by changing the length of the string sent to `process-send-string`.
```
DEFUN ("process-send-string", Fprocess_send_string, Sprocess_send_string,
2, 2, 0,
doc: /* Send PROCESS the contents of STRING as input.
PROCESS may be a process, a buffer, the name of a process or buffer, or
nil, indicating the current buffer's process.
If STRING is larger than …
```
> Fix 1550: Minimize length of string sent to process-send-string

- Cask
- elpy.el
Simple patch to adapt to an incompatibility introduced by ffip ≥ 6.0.0.  `project-root` appears to be default now, and support for filtering by subdir within project-root appears to have been dropped.
* Tests broken by ffip-project-search's changed arguments now pass, but numerous unrelated issues exist elsewhere.
> Update ffip-project-search arguments for ffip >= 6.0.0

- elpy-django.el
Fixes a typo in the docstring for `elpy-django--get-test-format`
> Fix typo in docstring

- elpy-shell.el
This is removing an implicit dependency on `cl' and updating it to use `cl-lib'. `cl-lib' is already a dependency.
> Use cl-lib when trying to use eval-sexp-fu-flash

- elpy-refactor.el
elpy-refactor: use the symbol to be renamed for initial input when prompting for new name
> elpy-refactor: use the symbol to be renamed for initial input when prompting for new name

- elpy/json_encoder.py
- elpy/rpc.py
- elpy/tests/support.py
- requirements-rpc.txt
This PR implements basic compatibility with jedi 18.0.  The issue was that the default json serializer used by python json.dumps could not handle `pathlib.Path` objects. This PR addresses the issue by extending the default JSONEncoder class. `pathlib.Path` objects are converted to str before encoding them to json.
Test are not really passing BUT the tests were not passing before this change anyway. At least some more tests are passing now.
> Implement rudimentary compatibility with jedi 18.0

- docs/introduction.rst
Add/replace `python3-autopep8`, `yapf3`, and `python3-yapf` in the library installation command for Debian like systems
> Update libraries for Python3

- elpy-rpc.el
The `.eln` files created by the native compile feature are not located in the same folder as the `.el` and `.elc` files they are derived from. This means that using `(locate-library "elpy")` to find the right folder for `elpy-rpc-pythonpath` breaks because it returns something like `"/home/tom/.emacs.d/elpa/elpy-20200527.2021/eln-x86_64-pc-linux-gnu-2ca71878e862259e/"` instead of `"/home/tom/.emacs.d/elpa/elpy-20200527.2021/"`. Using `(locate-library "elpy.el")` instead fixes the issue.
@AndreaCorallo Do you have an idea of the extent to which this will be an issue? In other words, how many codebases make use of `locate-library` in ways that will cause bugs that are similar to this? Probably just something to keep an eye on for the changelog for emacs 28, but might be worth starting some …
> change elpy-rpc-pythonpath to support native-comp

- elpy/blackutil.py
Fixes https://github.com/jorgenschaefer/elpy/issues/1949
This changes how black configuration is loaded. Instead of looking for
`pyproject.toml` directly, use a black to load the configuration in the
same way the black CLI would. This allows for other configuration
files to be considered, such as `~/.black` or `~/.config/black`.
> Use black for loading black config

- elpy-rpc.el
- scripts/setup
On a fresh install of Ubuntu Server 20.04, python is not symlinked to python3, so elpy does not work out of the box. See https://github.com/jorgenschaefer/elpy/issues/1940 for details. Changes to elpy-rpc.el fix this.
Tests using python3 did not pass in my environment. Changes to scripts/test fix this.
N/A. This PR contains no new features.
> fixes https://github.com/jorgenschaefer/elpy/issues/1940, tests

- elpy.el
Ignore warnings coming from `yapf`
> Ignore warnings coming from `yapf`

- elpy/blackutil.py
Prior to this, the return value of `black.files.find_pyproject_toml` was passed directly
to `os.path.exists`. This was fine where `black` could find a `pyproject.toml` file.
However, when one cannot be located, `find_pyproject_toml` returns `None`, which results
in an uncaught exception from `os.path.exists`. This adds an additional check for when
`find_project_toml` returns `None`.
Fixes #1955 (introduced by #1950).
_**I have only run Python-based tests, which were not passing before I submitted this PR. I have verified that this PR introduces no new Python test failures. In fact it fixes three of the four existing failures in my local testing. (See [this comment](#issuecomment-1011735002) …
> FIXES REGRESSION - Accommodates black.files.find_pyproject_toml returning None

- elpy.el
Added `(require 'hideshow')` to elpy .py since `hs-life-goes-on` is a macro, so its definition has to be available when the code using it is being loaded or byte-compiled.
fixes
- https://github.com/jorgenschaefer/elpy/issues/1824
- https://emacs.stackexchange.com/questions/58956/unable-to-fold-code-in-elpy
- https://emacs.stackexchange.com/questions/54213/code-folding-in-elpy-not-working
All tests that pass in master pass in in the PR.
> fix #1824 & other hs-life-goes-on related errors when folding

- elpy-shell.el
* elpy-shell.py (elpy-shell-get-or-create-process): Pass 'remote'
argument to 'executable-find' to enable remote executable search.
> Fix bug#1917: elpy-shell-get-or-create-process fails for remote files

- elpy/tests/test_jedibackend.py
This commit changes the regex string that matches against the arguments
of `json.loads` in the Python library. It removes the explicit
reference to the "encoding" keyword argument that was removed in
Python 3.6+.
This commit fixes issue #1968. The test `RPCGetDocstringTests.test_should_get_docstring` in elpy/tests/support.py now passes for versions (3.6+) of Python where the "encoding" keyword has been removed from the signature of `json.loads`. 
Since the "encoding.\* " portion of the regex was preceded by a greedy wildcard, the new version of the regex will work regardless of whether this keyword is present in the `json.loads` signature.
- [ X ] Commits respect our …
> Fix #1968 - test_should_get_docstring fails for Python 3.6+

- elpy-shell.el
This change creates a custom variable that allows MacOS users to decide
whether to use a pipe or a pseudo-terminal (pty) to connect to the Python
shell when `elpy-shell-get-or-create-process` is called. Before this commit,
all Mac users are forced to use a pipe if the Python shell is created using
this function, even though this is not necessary for all users.
Some MacOS users experience issues connecting to the Python shell using a
pty. One of major problems is the inability to send greater than 1024
characters to the shell at one time. These issues are caused by versions of
Python that use the libedit version of Readline rather than the GNU
version. By default, MacOS does not have GNU Readline installed, so it instead
uses the libedit version for the versions of Python built into the …
> Fix #1867 - allow MacOS users to choose pty or pipe for Python shell

- elpy.el
If using flycheck or some message utility while in a function,
having elpy-eldoc-show-current-function set to nil will cause
eldoc to delete any visible message in the echo area.
> Fix issue with eldoc when elpy-eldoc-show-current-function is nil

- .github/workflows/test.yml
Issue: https://github.com/actions/setup-python/issues/672
Also fixes CI to get it to actually start running the tests again and not fail on setup
> Remove support for Python 2.7 and fix broken CI setup flow

- elpy.el
Adds a note about the requirement of 'toml' to be installed for the use of the `elpy-black-fix-code` function.
Closes #2004 and #2008
> Document need of toml with black formatter

- elpy/blackutil.py
- elpy/jedibackend.py
running `./scripts/test python` reports the following problems:
```
======================================================================
ERROR: test_fix_code (tests.test_yapf.YAPFTestCase.test_fix_code)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/hoel/work/code-root/github.com/elpy/elpy/yapfutil.py", line 31, in fix_code
reformatted_source, _ = yapf_api.FormatCode(code,
^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FormatCode() got an unexpected keyword argument 'verify'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```
> Replace pkg_resources.parse_version by packaging.version.Version

- test/elpy-config--insert-help-test.el
- test/elpy-library-root-test.el
- test/elpy-open-and-indent-line-above-test.el
- test/elpy-rpc-get-usages-test.el
- test/elpy-rpc-test.el
Fix tests with duplicate names.  When I tried to run the ert tests, they failed repeatedly, giving errors from tests which had duplicate names. I have tracked these down and replaced them with unique names.
This would be a necessary first step to getting the tests to run again, and generally updating elpy.
Tests do not pass properly, but they do not pass on `master`, either.  Failing tests are:
```
23 unexpected results:
FAILED  elpy-company-backend-should-add-shell-candidates
FAILED  elpy-company-backend-should-find-full-prefix-string
FAILED  elpy-company-backend-should-find-simple-prefix-string
FAILED  elpy-config--get-config-should-return-keys
FAILED …
```
> Fix duplicate names in test library.

- elpy-pkg.el
The information in `<name>-pkg.el` did not agree with the information in `<name>.el`.  This pull-requests addresses that be removing the outdated `<name>-pkg.el`.
While the end-user package manager `package.el` expects a file `<name>-pkg.el`, this should only be generate by the package archive (such as GNU ELPA and MELPA), instead of being tracked in the upstream repository.
The tools used maintain the various *ELPA, do *not* use `<name>-pkg.el` as a data *source*, they only generate it it.
- `elpa-admin.el`, the tool used for GNU ELPA and NonGNU ELPA, does *not* use `<name>-pkg.el` as a data source and it never has.
- `package-build.el`, the tool used for Melpa, prefers `<name>.el` but *currently* falls back to get information missing from there from `<name>-pkg.el` instead. I am goint …
> Remove outdated `elpy-pkg.el`

- elpy-rpc.el
- test/elpy-rpc--get-pip-dependencies-test.el
In Python 3.12 (and later), the `distutils` module has been removed. This causes the _rpc_ environment to fail.  By installing `setuptools` as a third-party dependency for Python 3.12 and later, the currently missing dependencies will be added and the `elpy` Python code will work as expected.
Output from `elpy-config` for an `rpc-venv` created with Python 3.12:
```shell
There was an unexpected problem starting the RPC process. Please check
the following output to see if this makes sense to you. To me, it
doesn't.
Traceback (most recent call last):
File "<string>", line 9, in <module>
ModuleNotFoundError: No module named 'distutils'
```
As an alternative to the changes, there are workarounds such as:
```shell
~/.emacs.d/elpy/rpc-venv/bin/pip install setuptools 
```
fixes #2051 
fixes #2039 …
> fix(rpc): add support for Python 3.12 and later

- elpy.el
- elpy/blackutil.py
- elpy/jedibackend.py
- requirements-rpc.txt
Most of these are actually due to Christopher Genovese in discussion of #2051 
The most recent pull request fixes some of the 3.12 incompatibilities but some remain.
This fixes the startup python string in `elpy.el` and also some fixes to the `black` and `jedi` interfaces.  Finally, it updates `requirements.txt` with a conditional load of `distutils` or `packaging`.
Tests are broken beyond my ability to fix them.
> A number of additional fixes for newer python versions
